let lessons = [
  {
    "id": 1001,
    "subject": "Math",
    "price": 25.00,
    "location":"London",
    "image": "images/math.png",
    "availableInventory": 5,
    
  },
    {
      "id": 1002,
      "subject": "Math",
      "price": 25.00,
      "location":"New york",
      "image": "images/math.png",
      "availableInventory": 5,
    },
    {
      "id": 1003,
      "subject": "English",
      "price": 20.00,
      "location":"Texas",
      "image": "images/english.png",
      "availableInventory": 5,
    },
    {
      "id": 1004,
      "subject": "English",
      "price": 20.00,
      "location":"Houston",
      "image": "images/english.png",
      "availableInventory": 5,
    },
    {
      "id": 1005,
      "subject": "Music",
      "price": 12.00,
      "location":"Alabama",
      "image": "images/music.png",
      "availableInventory": 5,
    },
    {
        "id": 1006,
        "subject": "Music",
        "price": 12.00,
        "location":"London",
        "image": "images/music.png",
        "availableInventory": 5,
      },
      {
        "id": 1007,
        "subject": "Physics",
        "price": 15.00,
        "location":"Alabama",
        "image": "images/physics.png",
        "availableInventory": 5,
      },
      {
        "id": 1008,
        "subject": "Physics",
        "price": 15.00,
        "location":"Texas",
        "image": "images/physics.png",
        "availableInventory": 5,
      },
      {
        "id": 1009,
        "subject": "Health education",
        "price": 14.00,
        "location":"New york",
        "image": "images/health.png",
        "availableInventory": 5,
      },
      {
        "id": 1010,
        "subject": "Health education",
        "price": 14.00,
        "location":"Houston",
        "image": "images/health.png",
        "availableInventory": 5,
      },
     
  ]